on:
  workflow_dispatch:
  push:
    paths:
      - penguins.Rmd

name: Render report

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        
      - name: build report
        run: make analysis/penguins.html
